FROM python:3.13-alpine
WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app/
CMD [ "uvicorn", "main:api", "--host", "0.0.0.0", "--port", "8000" ]